-- Authors: Spencer Hirsch, shirsch2020@my.fit.edu
--          Tyler Gutowski, tgutowski2020@my.fit.edu
-- Course:  CSE 4250, Fall 2022
-- Project: Project 3, Can you HEAR me now?
WITH ADA.TEXT_IO;
WITH ADA.TEXT_IO.UNBOUNDED_IO;
WITH ADA.STRINGS;
WITH ADA.STRINGS.FIXED;
WITH ADA.INTEGER_TEXT_IO;
WITH ADA.CONTAINERS.DOUBLY_LINKED_LISTS;
WITH ADA.STRINGS.UNBOUNDED;
USE ADA.STRINGS.UNBOUNDED;

PACKAGE GRAPH IS
	ALREADY_PRINTED_DFS: BOOLEAN;
	TYPE TOWERS;                                -- DECLARE TYPE
	TYPE TOWERS_ACCESS IS ACCESS TOWERS;        -- REFERNCE TO THE TYPE

	-- INITIALIZE DOUBLY LINKED LIST OF TYPE TOWER_ACCESS
	PACKAGE LINKS IS NEW ADA.CONTAINERS.DOUBLY_LINKED_LISTS(TOWERS_ACCESS);
	USE LINKS;

	-- TYPE THAT STORES THE NECESSARY DATA FOR EACH TOWER
	-- EACH TOWER HAS A SOURCE AND A LIST OF CONNECTING TOWERS
	TYPE TOWERS IS RECORD
    SOURCE : UNBOUNDED_STRING;
    LINK : LIST;                            -- LIST OF TOWER_ACCESS
    CHECKED : BOOLEAN := FALSE;
	END RECORD; 

	-- DECLARE LIST WITHIN SCOPE OF MAIN PROCEDURE

	SOURCES : LIST;
	FUNCTION EXISTS_IN_SOURCE (TOWER_FIRST_NAME : STRING) RETURN BOOLEAN;

	FUNCTION GET_FROM_SOURCE ( TOWER_FIRST_NAME : STRING ) RETURN TOWERS_ACCESS;

	PROCEDURE DFS (TOWER_FIRST_NAME : STRING; TOWER_SECOND_NAME : STRING; TRUE_TOWER_FIRST_NAME : STRING);

	FUNCTION CHECK_TOWER_LIST(TOWER_FIRST_NAME : STRING; TOWER_SECOND_NAME : STRING) RETURN BOOLEAN;

	FUNCTION CHECK_ALL_POSSIBLE(TOWER_FIRST_NAME : STRING; TOWER_SECOND_NAME : STRING) RETURN BOOLEAN;
END GRAPH;
	
