-- Authors: Spencer Hirsch, shirsch2020@my.fit.edu
--          Tyler Gutowski, tgutowski2020@my.fit.edu
-- Course:  CSE 4250, Fall 2022
-- Project: Project 3, Can you HEAR me now?

WITH ADA.CONTAINERS.DOUBLY_LINKED_LISTS;
WITH ADA.CONTAINERS.VECTORS;
WITH ADA.STRINGS.UNBOUNDED;

PACKAGE GRAPH IS
	PROCEDURE ADD_NODE(FIRST_NAME : STRING; SECOND_NAME : STRING; COMMAND : STRING);
	TYPE TOWERS;
	TYPE TOWERS_ACCESS IS ACCESS TOWERS;
	PACKAGE LINKS IS NEW Ada.Containers.Doubly_Linked_Lists(TOWERS_ACCESS);
	TYPE TOWERS IS RECORD
        SOURCE : STRING(1..50);
	END RECORD;

	PACKAGE TOWER_LIST IS NEW ADA.CONTAINERS.DOUBLY_LINKED_LISTS(TOWERS);

END GRAPH;